/**
 * Complete catalog of 46 GoogleCloudPlatform/cloud-solutions projects
 * evaluated across Migrate, Modernize, and Build in the MMB Github Assets Assessment.
 * @module @deepseek-ai/dsh-mmb-migration-workbench/catalog-data
 */

import type { MmbAsset } from './types.ts'

export const MMB_ASSETS: readonly MmbAsset[] = [
  // ── MIGRATE (7 Projects) ───────────────────────────────────────────────────
  {
    id: 'hadoop-to-lakehouse-migration-demo',
    name: 'Hadoop to Lakehouse Migration Demo',
    domain: 'migrate',
    rank: 1,
    codeFiles: 35,
    hasTests: false,
    score: 2.6,
    realityCheck: 'Standard Dataproc + BigLake + Iceberg reference architecture. Simulates HDFS to GCS migration with Dataplex governance. Standard shell/Terraform scripts; lacks automated migration intelligence.',
    marketFit2026: 'High (Hadoop / Cloudera exit to BigLake & Dataproc)',
    antigravityRecommendation: 'Build AGY Data Migration Assistant wrapper. Add automated schema drift and data validation hooks via AGY SDK.',
    targetGcpServices: ['Dataproc', 'BigLake', 'Apache Iceberg', 'Dataplex', 'Cloud Storage'],
    tags: ['hadoop', 'hdfs', 'lakehouse', 'iceberg', 'biglake', 'dataplex'],
    status: 'promising',
  },
  {
    id: 'mmb-datacloud',
    name: 'MMB DataCloud (Database Migration Labs)',
    domain: 'migrate',
    rank: 2,
    codeFiles: 10,
    hasTests: true,
    score: 2.2,
    realityCheck: 'Qwiklabs training lab scripts. Terraform and load scripts for SQL Server and Postgres to AlloyDB migration. Basic lab exercise, not an enterprise migration system.',
    marketFit2026: 'Moderate (AlloyDB database consolidation)',
    antigravityRecommendation: 'Bundle into AGY Database Migration Suite. Add automated schema conversion validation.',
    targetGcpServices: ['AlloyDB', 'Cloud SQL', 'Database Migration Service'],
    tags: ['sql-server', 'postgres', 'alloydb', 'dms', 'qwiklabs'],
    status: 'promising',
  },
  {
    id: 'migrate-from-aws-to-google-cloud',
    name: 'Migrate from AWS to Google Cloud',
    domain: 'migrate',
    rank: 3,
    codeFiles: 38,
    hasTests: true,
    score: 2.2,
    realityCheck: '2021-era manual migration scripts. Terraform and shell for EKS-to-GKE proxy and S3-to-GCS. Superseded by modern automated tooling.',
    marketFit2026: 'Moderate (AWS to GCP enterprise migrations)',
    antigravityRecommendation: 'Migrate scripts into AGY CLI Discovery Skill. Automate AWS API discovery via boto3 and generate GCP equivalents.',
    targetGcpServices: ['GKE', 'Cloud Storage Transfer Service', 'VPC Network Peering'],
    tags: ['aws', 'eks', 's3', 'gke', 'storage-transfer'],
    status: 'promising',
  },
  {
    id: 'gemini-powered-migrations-to-google-cloud',
    name: 'Gemini-Powered Migrations to Google Cloud',
    domain: 'migrate',
    rank: 4,
    codeFiles: 110,
    hasTests: false,
    score: 1.9,
    realityCheck: 'Mock JSON test files + TOML prompt templates. Evaluates AWS S3, Lambda, and Azure Blob. Depends on deprecated legacy CLI structure.',
    marketFit2026: 'High (Automated multi-cloud discovery assessments)',
    antigravityRecommendation: 'Priority: Re-package as AGY Extension (gemini-migration-extension). Add Python boto3 MCP server for live AWS discovery.',
    targetGcpServices: ['Cloud Run', 'Cloud Functions', 'Cloud Storage'],
    tags: ['aws', 'lambda', 's3', 'azure-blob', 'discovery', 'assessment'],
    status: 'demo',
  },
  {
    id: 'migrate-from-azure-to-google-cloud',
    name: 'Migrate from Azure to Google Cloud',
    domain: 'migrate',
    rank: 5,
    codeFiles: 10,
    hasTests: false,
    score: 1.3,
    realityCheck: 'Pure markdown documentation. Covers Azure VMs, AKS, Blob Storage, and Azure SQL. Zero executable code.',
    marketFit2026: 'Moderate (Azure to GCP compete)',
    antigravityRecommendation: 'Rewrite as AGY Azure Migration Skill. Implement automated discovery via Azure SDK.',
    targetGcpServices: ['Compute Engine', 'GKE', 'Cloud SQL', 'Cloud Storage'],
    tags: ['azure', 'aks', 'blob-storage', 'azure-sql', 'docs-only'],
    status: 'demo',
  },
  {
    id: 'migrate-nutanix-to-google-cloud',
    name: 'Migrate Nutanix to Google Cloud',
    domain: 'migrate',
    rank: 6,
    codeFiles: 3,
    hasTests: false,
    score: 1.2,
    realityCheck: '3-page markdown marketing brief covering Nutanix Cloud Clusters (NC2) on Bare Metal. Zero code or Terraform.',
    marketFit2026: 'Moderate (Bare Metal on GCP)',
    antigravityRecommendation: 'Static Solution Brief. Keep as sales enablement text only.',
    targetGcpServices: ['Google Cloud Bare Metal', 'NC2'],
    tags: ['nutanix', 'nc2', 'bare-metal', 'docs-only'],
    status: 'demo',
  },
  {
    id: 'hive-bigquery-connector-demo',
    name: 'Hive BigQuery Connector Demo',
    domain: 'migrate',
    rank: 7,
    codeFiles: 3,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub. Points to historic commit hash.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['BigQuery'],
    tags: ['hive', 'bigquery', 'archived'],
    status: 'archived',
  },

  // ── MODERNIZE (18 Projects) ───────────────────────────────────────────────
  {
    id: 'oracle-bigquery-mcp-agent',
    name: 'Oracle to BigQuery MCP Agent',
    domain: 'modernize',
    rank: 1,
    codeFiles: 55,
    hasTests: true,
    score: 3.5,
    realityCheck: 'Top-tier SA POC. Working FastAPI Model Context Protocol (MCP) server, Oracle 19c on GCE, Datastream CDC to BigQuery, BQML ARIMA_PLUS forecasting. Lacks enterprise auth & rate-limiting.',
    marketFit2026: 'High (Oracle Database Exit, CDC streaming, In-Database AI)',
    antigravityRecommendation: 'Deploy as AGY Managed Agent & MCP Server. Register in .agy/mcp.json. Expose live Oracle forecasting tools directly to AGY CLI and Antigravity Desktop.',
    targetGcpServices: ['BigQuery', 'Datastream', 'BQML', 'FastAPI', 'Compute Engine'],
    tags: ['oracle', 'bigquery', 'mcp', 'cdc', 'datastream', 'bqml', 'fastapi'],
    status: 'top-tier',
  },
  {
    id: 'k8s-hybrid-neg-controller',
    name: 'Kubernetes Hybrid NEG Controller',
    domain: 'modernize',
    rank: 2,
    codeFiles: 27,
    hasTests: true,
    score: 3.2,
    realityCheck: 'Real Go Kubernetes Controller (2.6k LOC). Manages hybrid NEGs (NON_GCP_PRIVATE_IP_PORT) for Cloud Load Balancing across on-prem/multicloud. Niche infra tool.',
    marketFit2026: 'Moderate (Hybrid multi-cloud ingress routing & enterprise interconnect)',
    antigravityRecommendation: 'Package as AGY Managed Infra Daemon. Autonomous reconciliation daemon for hybrid multi-cloud ingress routing.',
    targetGcpServices: ['GKE', 'Cloud Load Balancing', 'Network Endpoint Groups'],
    tags: ['kubernetes', 'go', 'controller', 'neg', 'hybrid-cloud', 'load-balancing'],
    status: 'top-tier',
  },
  {
    id: 'operational-ai-leap',
    name: 'Operational AI Leap (AlloyDB ScaNN + BigQuery Zero-ETL)',
    domain: 'modernize',
    rank: 3,
    codeFiles: 29,
    hasTests: false,
    score: 3.0,
    realityCheck: 'Strong marketing narrative, medium code depth. AlloyDB pgvector + ScaNN + BigQuery zero-copy federation. Core ML logic is in a Colab notebook; demo app is a toy Angular shop.',
    marketFit2026: 'High (Zero-ETL AI, pgvector, Vector Search in operational DBs)',
    antigravityRecommendation: 'Convert Colab into AGY SDK Agent Skill. Replace manual notebook with an AGY Python SDK script running automated embedding and hybrid search.',
    targetGcpServices: ['AlloyDB', 'pgvector', 'ScaNN', 'BigQuery Federation', 'Vertex AI'],
    tags: ['alloydb', 'pgvector', 'scann', 'bigquery', 'zero-etl', 'vector-search'],
    status: 'promising',
  },
  {
    id: 'dataflow-bigquery-change-data-capture',
    name: 'Dataflow BigQuery CDC Pipeline',
    domain: 'modernize',
    rank: 4,
    codeFiles: 20,
    hasTests: true,
    score: 2.8,
    realityCheck: 'Solid Java Beam CDC pipeline. Streams Spanner CDC mutations into BigQuery with deduplication. Standard data engineering; lacks AI agentic differentiation.',
    marketFit2026: 'Moderate (Spanner to BigQuery real-time analytics)',
    antigravityRecommendation: 'Maintain as Core Streaming Blueprint. Retain as a standard Dataflow reference implementation.',
    targetGcpServices: ['Dataflow', 'Cloud Spanner', 'BigQuery', 'Apache Beam'],
    tags: ['dataflow', 'java', 'beam', 'cdc', 'spanner', 'bigquery'],
    status: 'promising',
  },
  {
    id: 'arm-reference-guides',
    name: 'Arm Reference Guides (Axion / Tau T2A Profiling)',
    domain: 'modernize',
    rank: 5,
    codeFiles: 62,
    hasTests: true,
    score: 2.8,
    realityCheck: 'Complete benchmarking suite. Tau T2A / Axion Arm performance profiling, Terraform, and Docker cross-compilation. Mostly shell scripts and Terraform configs.',
    marketFit2026: 'Moderate (Google Cloud Axion Arm processor push)',
    antigravityRecommendation: 'Create AGY Arm Profiling Skill (/arm-audit). Automated AGY CLI skill to scan customer Dockerfiles/C++ builds for Arm compatibility.',
    targetGcpServices: ['Compute Engine (Axion / Tau T2A)', 'Artifact Registry', 'Cloud Build'],
    tags: ['arm', 'axion', 'tau-t2a', 'benchmarking', 'docker', 'terraform'],
    status: 'promising',
  },
  {
    id: 'gke-migration-agent',
    name: 'GKE Migration Agent (ingress2gateway AST Translator)',
    domain: 'modernize',
    rank: 6,
    codeFiles: 7,
    hasTests: true,
    score: 2.7,
    realityCheck: 'Promising prototype (ingress2gateway). Python AST scanner & translator for GKE Ingress to Gateway API. Unhardened; fails on complex annotations/custom ingress plugins.',
    marketFit2026: 'High (GKE Gateway API modernization push)',
    antigravityRecommendation: 'Promote to Official AGY CLI Skill (/ingress2gateway). Run agy run /ingress2gateway for interactive cluster scan and manifest translation.',
    targetGcpServices: ['GKE', 'Gateway API', 'GKE Ingress'],
    tags: ['gke', 'ingress', 'gateway-api', 'python', 'ast-translation', 'k8s'],
    status: 'promising',
  },
  {
    id: 'legacy-detox-demo',
    name: 'Legacy Detox Demo (PySpark to Dataproc/BigQuery)',
    domain: 'modernize',
    rank: 7,
    codeFiles: 17,
    hasTests: false,
    score: 2.7,
    realityCheck: 'PySpark to Dataproc/BigQuery modernizer. Unverified against SQL hallucination; lacks deterministic AST parsing (like Moderne/OpenRewrite).',
    marketFit2026: 'High (Hadoop exit, PySpark modernization)',
    antigravityRecommendation: 'Package as AGY Modernization Skill (/legacy-detox). Combine LLM translation with deterministic AST verification rules.',
    targetGcpServices: ['Dataproc Serverless', 'BigQuery', 'BigLake'],
    tags: ['pyspark', 'spark', 'dataproc', 'bigquery', 'hadoop-exit', 'ast'],
    status: 'promising',
  },
  {
    id: 'dataflow-gcs-to-alloydb',
    name: 'Dataflow GCS to AlloyDB Batch Ingestion',
    domain: 'modernize',
    rank: 8,
    codeFiles: 7,
    hasTests: true,
    score: 2.3,
    realityCheck: 'Standard batch ingestion template. Java Beam template uploading CSV/Avro to AlloyDB. Routine utility, zero novelty.',
    marketFit2026: 'Low',
    antigravityRecommendation: 'Retain as Utility Pipeline.',
    targetGcpServices: ['Dataflow', 'AlloyDB', 'Cloud Storage'],
    tags: ['dataflow', 'alloydb', 'avro', 'beam'],
    status: 'utility',
  },
  {
    id: 'serverless-event-processing',
    name: 'Serverless Event Processing',
    domain: 'modernize',
    rank: 9,
    codeFiles: 13,
    hasTests: true,
    score: 2.0,
    realityCheck: '101-level tutorial architecture. Eventarc + Cloud Run + Firestore. Elementary sample found in standard GCP docs.',
    marketFit2026: 'Low',
    antigravityRecommendation: 'Standard Reference Blueprint.',
    targetGcpServices: ['Eventarc', 'Cloud Run', 'Firestore'],
    tags: ['eventarc', 'cloud-run', 'firestore', 'serverless'],
    status: 'utility',
  },
  {
    id: 'dotnet-modernization-demo',
    name: '.NET Modernization Demo (ContosoUniversity to Cloud Run)',
    domain: 'modernize',
    rank: 10,
    codeFiles: 87,
    hasTests: true,
    score: 2.0,
    realityCheck: 'Copied Microsoft sample app. Literally Microsoft open-source ContosoUniversity (2017) copied into repo with prompt text. No real automated tooling.',
    marketFit2026: 'High (Azure compete, Windows to Linux containerization)',
    antigravityRecommendation: 'Convert Prompts into AGY Spec-Driven Skill (/modernize-dotnet). Enforce build-verified dotnet build loop in AGY CLI.',
    targetGcpServices: ['Cloud Run', 'GKE', 'Cloud SQL for SQL Server'],
    tags: ['dotnet', 'csharp', 'contoso', 'cloud-run', 'containerization'],
    status: 'demo',
  },
  {
    id: 'java-modernization-demo',
    name: 'Java Modernization Demo (Spring Boot to GCP)',
    domain: 'modernize',
    rank: 11,
    codeFiles: 9,
    hasTests: true,
    score: 1.8,
    realityCheck: 'Minimal Terraform + Markdown prompt guide. Relies on manual copy-pasting of instructions.',
    marketFit2026: 'High (Java enterprise compete against AWS / Azure)',
    antigravityRecommendation: 'Expand into AGY Lossless Migration Pipeline. Integrate with OpenRewrite/Moderne recipes to eliminate LLM hallucinations.',
    targetGcpServices: ['Cloud Run', 'GKE', 'Cloud SQL', 'Artifact Registry'],
    tags: ['java', 'spring-boot', 'cloud-run', 'openrewrite', 'containerization'],
    status: 'demo',
  },
  {
    id: 'alloydb-auth-workload-identity',
    name: 'AlloyDB Auth with Workload Identity',
    domain: 'modernize',
    rank: 12,
    codeFiles: 2,
    hasTests: false,
    score: 1.1,
    realityCheck: '2-page documentation snippet on IAM auth with AlloyDB. Zero executable code.',
    marketFit2026: 'Low',
    antigravityRecommendation: 'Documentation Guide.',
    targetGcpServices: ['AlloyDB', 'IAM Workload Identity'],
    tags: ['alloydb', 'iam', 'workload-identity', 'docs-only'],
    status: 'demo',
  },
  {
    id: 'alloydb-autoscaler',
    name: 'AlloyDB Autoscaler (Archived)',
    domain: 'modernize',
    rank: 13,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub. Superseded by native AlloyDB autoscaling.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['AlloyDB'],
    tags: ['alloydb', 'autoscaler', 'archived'],
    status: 'archived',
  },
  {
    id: 'alloydbomni-ha-patroni-etcd',
    name: 'AlloyDB Omni HA Patroni ETCD (Archived)',
    domain: 'modernize',
    rank: 14,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['AlloyDB Omni'],
    tags: ['alloydb-omni', 'patroni', 'archived'],
    status: 'archived',
  },
  {
    id: 'dataflow-gcs-avro-to-spanner-scd',
    name: 'Dataflow GCS Avro to Spanner SCD (Archived)',
    domain: 'modernize',
    rank: 15,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Cloud Spanner'],
    tags: ['spanner', 'dataflow', 'archived'],
    status: 'archived',
  },
  {
    id: 'dataflow-kafka-to-bigquery',
    name: 'Dataflow Kafka to BigQuery (Archived)',
    domain: 'modernize',
    rank: 16,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub. Superseded by native Dataflow templates.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['BigQuery', 'Dataflow'],
    tags: ['kafka', 'bigquery', 'dataflow', 'archived'],
    status: 'archived',
  },
  {
    id: 'gke-optimization',
    name: 'GKE Optimization (Archived)',
    domain: 'modernize',
    rank: 17,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['GKE'],
    tags: ['gke', 'optimization', 'archived'],
    status: 'archived',
  },
  {
    id: 'sa-tools',
    name: 'SA Tools (Archived)',
    domain: 'modernize',
    rank: 18,
    codeFiles: 5,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Google Cloud'],
    tags: ['sa-tools', 'archived'],
    status: 'archived',
  },

  // ── BUILD (21 Projects) ───────────────────────────────────────────────────
  {
    id: 'confidential-ai-model-serving',
    name: 'Confidential AI Model Serving (AMD SEV-SNP Enclave)',
    domain: 'build',
    rank: 1,
    codeFiles: 25,
    hasTests: true,
    score: 3.4,
    realityCheck: 'Production-minded security enclave. Hardware-enforced AMD SEV-SNP + vTPM remote attestation with vLLM in Java/Terraform. Highly complex manual setup; narrow niche.',
    marketFit2026: 'High (Regulated AI, FSI, Healthcare, Privacy Enclaves)',
    antigravityRecommendation: 'Integrate with AGY Security Harness. Use as reference architecture for deploying AGY Managed Agents in strict privacy-isolated enclaves.',
    targetGcpServices: ['Confidential Space', 'Compute Engine (AMD SEV-SNP)', 'vLLM', 'Cloud KMS'],
    tags: ['confidential-ai', 'sev-snp', 'vtpm', 'attestation', 'vllm', 'security'],
    status: 'top-tier',
  },
  {
    id: 'build-with-gemini-demo',
    name: 'Build with Gemini Demo (Agentic Microservice Generator)',
    domain: 'build',
    rank: 2,
    codeFiles: 28,
    hasTests: true,
    score: 2.8,
    realityCheck: 'Agentic DDD microservice generator. Includes Playwright UI tests and PR reviews. Hardcoded to deprecated Gemini CLI branding; prompts need updating for Antigravity.',
    marketFit2026: 'High (AI-Led Development, DDD Microservice Scaffolding)',
    antigravityRecommendation: 'Re-baseline on AGY CLI / Antigravity Desktop. Convert into native AGY Skills with build-verification loops (mvn test, dotnet build).',
    targetGcpServices: ['Vertex AI Gemini', 'Cloud Build', 'Cloud Run'],
    tags: ['gemini', 'ddd', 'microservices', 'playwright', 'code-generation'],
    status: 'promising',
  },
  {
    id: 'ai',
    name: 'AI (Agent Development Kit & Marketing Suite)',
    domain: 'build',
    rank: 3,
    codeFiles: 264,
    hasTests: true,
    score: 2.5,
    realityCheck: 'Bloated code repository. Contains ADK, marketing agents, and PMax integrations. Duplicated Streamlit UI code and decaying SDK calls.',
    marketFit2026: 'Moderate (Multi-agent enterprise apps)',
    antigravityRecommendation: 'Refactor into AGY SDK Multi-Agent Harness. Prune duplicated frontend code and standardize on clean AGY SDK multi-agent patterns.',
    targetGcpServices: ['Vertex AI', 'Cloud Run', 'BigQuery'],
    tags: ['adk', 'multi-agent', 'marketing', 'streamlit', 'gemini'],
    status: 'promising',
  },
  {
    id: 'generative-media-shot-production',
    name: 'Generative Media Shot Production',
    domain: 'build',
    rank: 4,
    codeFiles: 8,
    hasTests: false,
    score: 2.4,
    realityCheck: 'ComfyUI JSON workflow configs (Imagen 3, Veo). Zero reusable backend code; purely static JSON node graphs for ComfyUI.',
    marketFit2026: 'Moderate (Studio Gen-Media & Visual Effects)',
    antigravityRecommendation: 'Convert ComfyUI workflows into AGY SDK Agents. Wrap generation pipelines into callable Python agent tools.',
    targetGcpServices: ['Vertex AI Imagen 3', 'Veo', 'Compute Engine GPU'],
    tags: ['imagen-3', 'veo', 'comfyui', 'media-generation'],
    status: 'promising',
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing Plant Ops Agent',
    domain: 'build',
    rank: 5,
    codeFiles: 18,
    hasTests: false,
    score: 2.2,
    realityCheck: 'Prompt wrappers for plant ops. Vertex AI Gemini with mock telemetry. Toy demo; lacks real integration with industrial OPC-UA or MQTT protocols.',
    marketFit2026: 'Moderate (Industrial IoT & Plant Telemetry)',
    antigravityRecommendation: 'Refactor into AGY Industrial Agent. Build real MQTT/SCADA connectors via Python AGY SDK.',
    targetGcpServices: ['Vertex AI', 'Pub/Sub', 'Cloud IoT Core (deprecated) / MQTT'],
    tags: ['manufacturing', 'industrial', 'opc-ua', 'mqtt', 'gemini'],
    status: 'demo',
  },
  {
    id: 'pino-logging-gcp-config',
    name: 'Pino Logging GCP Config',
    domain: 'build',
    rank: 6,
    codeFiles: 2,
    hasTests: true,
    score: 1.8,
    realityCheck: 'Simple npm logging helper. Formats Node.js JSON logs for Cloud Logging. Trivial utility library, not a cloud solution.',
    marketFit2026: 'Low',
    antigravityRecommendation: 'Maintain as Node.js npm package.',
    targetGcpServices: ['Cloud Logging'],
    tags: ['pino', 'logging', 'nodejs', 'npm'],
    status: 'utility',
  },
  {
    id: 'agentic-coding-with-data-agent-kit-demo',
    name: 'Agentic Coding with Data Agent Kit Demo',
    domain: 'build',
    rank: 7,
    codeFiles: 1,
    hasTests: false,
    score: 1.5,
    realityCheck: 'Self-serve Demo: 71-line SQL file and a README explaining concepts. No executable agent code.',
    marketFit2026: 'High (Data Agent Kit concept)',
    antigravityRecommendation: 'Flesh Out into Complete AGY SDK Blueprint. Provide real runnable LangGraph/ADK agent code.',
    targetGcpServices: ['BigQuery', 'Vertex AI', 'Data Agent Kit'],
    tags: ['data-agent-kit', 'adk', 'sql', 'agentic-coding'],
    status: 'demo',
  },
  {
    id: 'lab2life',
    name: 'Lab2Life (Bio-Pharma Lead Discovery)',
    domain: 'build',
    rank: 8,
    codeFiles: 2,
    hasTests: false,
    score: 1.4,
    realityCheck: 'Toy script (185 LOC). Basic Python script for bio-pharma lead discovery. Zero HPC or bioinformatics substance.',
    marketFit2026: 'Low',
    antigravityRecommendation: 'Archive or Rewrite with AGY Bio-Agent.',
    targetGcpServices: ['Vertex AI'],
    tags: ['bio-pharma', 'lab2life', 'python-script'],
    status: 'demo',
  },
  {
    id: 'nvidia-omniverse-on-google-cloud',
    name: 'NVIDIA Omniverse on Google Cloud',
    domain: 'build',
    rank: 9,
    codeFiles: 4,
    hasTests: false,
    score: 1.2,
    realityCheck: 'Markdown GKE setup docs. Code has been moved to marketplace.',
    marketFit2026: 'Low',
    antigravityRecommendation: 'Static GKE Setup Docs.',
    targetGcpServices: ['GKE', 'NVIDIA GPU'],
    tags: ['nvidia', 'omniverse', 'gke', 'docs-only'],
    status: 'demo',
  },
  // 12 Archived Stubs in Build
  {
    id: 'bulk-delete-gcs-files-fn',
    name: 'Bulk Delete GCS Files Function (Archived)',
    domain: 'build',
    rank: 10,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Cloud Storage', 'Cloud Functions'],
    tags: ['gcs', 'cloud-functions', 'archived'],
    status: 'archived',
  },
  {
    id: 'contextual-ai',
    name: 'Contextual AI (Archived)',
    domain: 'build',
    rank: 11,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub. Superseded by Vertex AI Search.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Vertex AI Search'],
    tags: ['contextual-ai', 'archived'],
    status: 'archived',
  },
  {
    id: 'conversational-commerce-agent',
    name: 'Conversational Commerce Agent (Archived)',
    domain: 'build',
    rank: 12,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Dialogflow', 'Vertex AI'],
    tags: ['commerce', 'dialogflow', 'archived'],
    status: 'archived',
  },
  {
    id: 'database-archival',
    name: 'Database Archival (Archived)',
    domain: 'build',
    rank: 13,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['BigQuery', 'Cloud Storage'],
    tags: ['database-archival', 'archived'],
    status: 'archived',
  },
  {
    id: 'fsi-quant-assistant',
    name: 'FSI Quant Assistant (Archived)',
    domain: 'build',
    rank: 14,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Vertex AI'],
    tags: ['fsi', 'quant', 'archived'],
    status: 'archived',
  },
  {
    id: 'imagen-object-changer',
    name: 'Imagen Object Changer (Archived)',
    domain: 'build',
    rank: 15,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Imagen'],
    tags: ['imagen', 'archived'],
    status: 'archived',
  },
  {
    id: 'imagen-voice-captioning',
    name: 'Imagen Voice Captioning (Archived)',
    domain: 'build',
    rank: 16,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Imagen', 'Speech-to-Text'],
    tags: ['imagen', 'speech', 'archived'],
    status: 'archived',
  },
  {
    id: 'serve-llm-app-using-gke',
    name: 'Serve LLM App Using GKE (Archived)',
    domain: 'build',
    rank: 17,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub. Moved to accelerated-platforms.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['GKE'],
    tags: ['gke', 'llm-serving', 'archived'],
    status: 'archived',
  },
  {
    id: 'speech2speech_translation',
    name: 'Speech2Speech Translation (Archived)',
    domain: 'build',
    rank: 18,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Translation API', 'Speech API'],
    tags: ['speech', 'translation', 'archived'],
    status: 'archived',
  },
  {
    id: 'speech2srt',
    name: 'Speech2SRT (Archived)',
    domain: 'build',
    rank: 19,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Speech API'],
    tags: ['speech', 'srt', 'archived'],
    status: 'archived',
  },
  {
    id: 'streamlit-pubsub',
    name: 'Streamlit PubSub (Archived)',
    domain: 'build',
    rank: 20,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Pub/Sub'],
    tags: ['streamlit', 'pubsub', 'archived'],
    status: 'archived',
  },
  {
    id: 'vision-ai-edge-platform',
    name: 'Vision AI Edge Platform (Archived)',
    domain: 'build',
    rank: 21,
    codeFiles: 1,
    hasTests: false,
    score: 0.6,
    realityCheck: 'Archived Stub.',
    marketFit2026: 'None',
    antigravityRecommendation: 'Purge from repository.',
    targetGcpServices: ['Vertex AI Vision'],
    tags: ['vision-ai', 'edge', 'archived'],
    status: 'archived',
  },
]
